services:
  mongodb:
    image: mongo:7.0.5
    container_name: mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: product-service
    volumes:
      - mongodb:/data/db
    networks:
      services-network:

  product-service:
    build: /product-service
    container_name: product-service
    restart: on-failure
    depends_on:
      - mongodb
      - discovery-server
    ports:
      - '8080:8080'
    networks:
      services-network:

  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - '3306:3306'
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      services-network:

  inventory-service:
    container_name: inventory-service
    build: /inventory-service
    ports:
      - '8082:8082'
    restart: on-failure
    depends_on:
      - mysql
      - discovery-server
    environment:
      DATABASE_HOST: mysql
      DATABASE_USER: root
      DATABASE_PASSWORD: ''
      DATABASE_NAME: inventory_service
      DATABASE_PORT: 3306
    networks:
      services-network:


  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: order-service
      POSTGRES_USER: kenti
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    expose:
      - "5431"
    ports:
      - "5431:5431"
    command: -p 5431
    networks:
      services-network:

  order-service:
    build: /order-service
    container_name: order-service
    restart: on-failure
    depends_on:
      - postgres
      - discovery-server
    ports:
      - '8081:8081'
    networks:
      services-network:

  discovery-server:
    build: /discovery-server
    container_name: discovery-server
    ports:
      - '8761:8761'
    networks:
      services-network:

  api-gateway:
    depends_on:
      - discovery-server
    ports:
      - 9000:9000
    container_name: api-gateway
    networks:
      - services-network
    build: /api-gateway

  #Keycloak
  keycloak-mysql:
    container_name: keycloak-mysql
    image: mysql:8
    volumes:
      - keycloak-mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    networks:
      services-network:

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.1
    command: [ "start-dev", "--import-realm"]
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8181:8080" #por defecto, keycloak corre en el 8080
    volumes:
      - ./docker/keycloak/realms:/opt/keycloak/data/import/
    depends_on:
      - keycloak-mysql
    networks:
      services-network:


networks:
  services-network:

volumes:
  mongodb:
  mysql:
  postgres:
  keycloak-mysql:
  keycloak: