spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8181/realms/microservice-course-realm


eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka
server:
  port: 9000

