spring:
  application:
    name: order-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5431/order-service
    username: kenti
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true
    properties:
        hibernate:
          globally_quoted_identifiers: true

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka  # localhost o nombre del contenedor : 8761 / eureka