spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://root:password@mongodb:27017/product-service?authSource=admin
server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka  # localhost o nombre del contenedor : 8761 / eureka