spring:
  application:
    name: inventory-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/inventory-service?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka  # localhost o nombre del contenedor : 8761 / eureka
