version: '3.7'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - '3306:3306'
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  inventory-service:
    build: .
    ports:
      - '8082:8082'
    depends_on:
      - mysql
    environment:
      DATABASE_HOST: mysql
      DATABASE_USER: root
      DATABASE_PASSWORD: ''
      DATABASE_NAME: inventory_service
      DATABASE_PORT: 3306
volumes:
  mysql:
